### ISSUE TITLE
What does mean file results.txt?

### ISSUE THREAD

**Issue by moddred** [Telariust/pollard-kangaroo#8]
Hello. What does mean file results.txt? Is it private keys for the problems? I checked, it is not.

**Comment by dem10** [comment]
This is the file where the found key is written.the program will create it when the key is found. Does the word «results» tell you nothing?all input data you specify in the batch file

**Comment by moddred** [comment]
Keys in the file "results" do not match to pubkeys spcified in the batch file.

**Comment by dem10** [comment]
so delete the old result file and run the check
python pollard-kangaroo.py 32 03b51474f995c573864e16ffd6424edba9c6310e1375867b4537d2b79aeb14371e
the private key will be indicated in the result file.in the batch file you need to specify number of bits and one public key and not a list of addresses
[usage] pollard-kangaroo [bits] [pubkey]
[usage] pollard-kangaroo [start:end] [pubkey]

**Comment by Telariust** [comment]
I worked a lot on random generation and custom key input.
Random keys are needed to evaluate real efficiency (the number of jumps per second is useless if the average length of the jump is not optimally selected).
The custom key through argv2 makes the script convenient to run (don’t need to edit the batch file every time).
As a result of these innovations, the public keys registered in the batch file (default_table) are now only used if
`elif not (Ntimeit> 1 and timeit_eachnewprvkey)`
Sorry for this unobvious behavior.
This will be fixed when the functionality of the name arguments is added so that the user can specify explicitly where load the public key from.
